"""Tests for icon_map.json coverage — verifies extracted icon mappings exist.

Freezes which item categories have working icon mappings after extraction.
Each test class covers one category with real item IDs and exact DDS paths
from the actual icon_map.json generated by the extraction pipeline.

These tests use the on-disk icon_map.json and game_catalogue.json as fixtures.
They verify the EXTRACTION is correct, not the RESOLUTION (that's in test_icon_provider.py).
"""

import json
from pathlib import Path

import pytest


DATA_DIR = Path(__file__).resolve().parent.parent.parent / "src" / "nmstoolkit" / "data"
ICONS_DIR = DATA_DIR / "icons"


@pytest.fixture(scope="module")
def icon_map():
    """Load the real icon_map.json from disk."""
    path = ICONS_DIR / "icon_map.json"
    if not path.exists():
        pytest.skip("icon_map.json not available (run icon extraction first)")
    return json.loads(path.read_text())


@pytest.fixture(scope="module")
def catalogue():
    """Load the real game_catalogue.json from disk."""
    path = ICONS_DIR / "game_catalogue.json"
    if not path.exists():
        pytest.skip("game_catalogue.json not available (run icon extraction first)")
    return json.loads(path.read_text())


def _assert_in_map(icon_map, item_id, expected_dds):
    """Assert item_id maps to expected DDS path (checking both bare and ^-prefixed)."""
    dds = icon_map.get(item_id, "") or icon_map.get("^" + item_id, "")
    assert dds == expected_dds, f"{item_id}: expected {expected_dds}, got {dds!r}"


# ---------------------------------------------------------------------------
# Category: Substances (minerals, gases, elements)
# User confirmed: icons correct on both Linux and Windows
# ---------------------------------------------------------------------------

class TestIconMapSubstances:
    """Substance items have correct DDS paths in icon_map."""

    def test_fuel1_carbon(self, icon_map):
        _assert_in_map(icon_map, "FUEL1", "TEXTURES/UI/FRONTEND/ICONS/U4SUBSTANCES/SUBSTANCE.FUEL.1.DDS")

    def test_oxygen(self, icon_map):
        _assert_in_map(icon_map, "OXYGEN", "TEXTURES/UI/FRONTEND/ICONS/U4SUBSTANCES/SUBSTANCE.AIR.1.DDS")

    def test_launchsub_dihydrogen(self, icon_map):
        _assert_in_map(icon_map, "LAUNCHSUB", "TEXTURES/UI/FRONTEND/ICONS/U4SUBSTANCES/SUBSTANCE.LAUNCHSUB.1.DDS")

    def test_land1_ferrite(self, icon_map):
        _assert_in_map(icon_map, "LAND1", "TEXTURES/UI/FRONTEND/ICONS/U4SUBSTANCES/SUBSTANCE.LAND.1.DDS")

    def test_catalyst1_sodium(self, icon_map):
        _assert_in_map(icon_map, "CATALYST1", "TEXTURES/UI/FRONTEND/ICONS/U4SUBSTANCES/SUBSTANCE.CATALYST.1.DDS")

    def test_substance_coverage(self, icon_map, catalogue):
        """At least 90 of ~107 substances should be in icon_map."""
        subs = catalogue["substances"]
        mapped = sum(1 for s in subs if s["id"] in icon_map or "^" + s["id"] in icon_map)
        assert mapped >= 90, f"Only {mapped} substances mapped, expected >= 90"


# ---------------------------------------------------------------------------
# Category: Products (crafted items, trade goods)
# User confirmed: icons correct
# ---------------------------------------------------------------------------

class TestIconMapProducts:
    """Product items have correct DDS paths in icon_map."""

    def test_casing(self, icon_map):
        _assert_in_map(icon_map, "CASING", "TEXTURES/UI/FRONTEND/ICONS/U4PRODUCTS/PRODUCT.CASING.DDS")

    def test_antimatter(self, icon_map):
        _assert_in_map(icon_map, "ANTIMATTER", "TEXTURES/UI/FRONTEND/ICONS/PRODUCTS/PRODUCT.ANTIMATTER.DDS")

    def test_microchip(self, icon_map):
        _assert_in_map(icon_map, "MICROCHIP", "TEXTURES/UI/FRONTEND/ICONS/U4PRODUCTS/PRODUCT.MICROCHIP.DDS")

    def test_product_coverage(self, icon_map, catalogue):
        """All products in catalogue should be in icon_map."""
        prods = catalogue["products"]
        mapped = sum(1 for p in prods if p["id"] in icon_map or "^" + p["id"] in icon_map)
        assert mapped == len(prods), f"{mapped}/{len(prods)} products mapped"


# ---------------------------------------------------------------------------
# Category: Multitool technologies
# User confirmed: icons correct on both platforms
# ---------------------------------------------------------------------------

class TestIconMapMultitoolTech:
    """Multitool base technologies have correct DDS paths."""

    def test_laser(self, icon_map):
        _assert_in_map(icon_map, "LASER", "TEXTURES/UI/FRONTEND/ICONS/TECHNOLOGY/RENDER.LASER1.DDS")

    def test_bolt(self, icon_map):
        _assert_in_map(icon_map, "BOLT", "TEXTURES/UI/FRONTEND/ICONS/TECHNOLOGY/RENDER.PROJECTILE1.DDS")

    def test_scan1(self, icon_map):
        _assert_in_map(icon_map, "SCAN1", "TEXTURES/UI/FRONTEND/ICONS/TECHNOLOGY/RENDER.SCAN.DDS")

    def test_grenade(self, icon_map):
        _assert_in_map(icon_map, "GRENADE", "TEXTURES/UI/FRONTEND/ICONS/TECHNOLOGY/RENDER.GRENADE.DDS")


# ---------------------------------------------------------------------------
# Category: Ship technologies
# User confirmed: icons correct on both platforms
# ---------------------------------------------------------------------------

class TestIconMapShipTech:
    """Ship base technologies have correct DDS paths."""

    def test_hyperdrive(self, icon_map):
        _assert_in_map(icon_map, "HYPERDRIVE", "TEXTURES/UI/FRONTEND/ICONS/TECHNOLOGY/RENDER.HYPERDRIVE.DDS")

    def test_pulsedrive(self, icon_map):
        _assert_in_map(icon_map, "SHIPJUMP1", "TEXTURES/UI/FRONTEND/ICONS/TECHNOLOGY/RENDER.PULSEDRIVE.DDS")

    def test_photon_cannon(self, icon_map):
        _assert_in_map(icon_map, "SHIPGUN1", "TEXTURES/UI/FRONTEND/ICONS/TECHNOLOGY/RENDER.SHIPPROJECTILE1.DDS")

    def test_launcher(self, icon_map):
        _assert_in_map(icon_map, "LAUNCHER", "TEXTURES/UI/FRONTEND/ICONS/TECHNOLOGY/RENDER.LANDINGGEAR.DDS")


# ---------------------------------------------------------------------------
# Category: Upgrade modules (UP_/UA_ prefixed)
# User confirmed: icons correct on both platforms
# ---------------------------------------------------------------------------

class TestIconMapUpgradeModules:
    """Upgrade modules have their own DDS paths in icon_map."""

    def test_up_laser1(self, icon_map):
        _assert_in_map(icon_map, "UP_LASER1", "TEXTURES/UI/FRONTEND/ICONS/TECHNOLOGY/RENDER.LASER1MOD.DDS")

    def test_up_laser4(self, icon_map):
        _assert_in_map(icon_map, "UP_LASER4", "TEXTURES/UI/FRONTEND/ICONS/TECHNOLOGY/RENDER.LASER1MOD.DDS")

    def test_upgrade_coverage(self, icon_map):
        """All UP_ entries should be in icon_map."""
        up_count = sum(1 for k in icon_map if k.startswith("UP_"))
        assert up_count >= 100, f"Only {up_count} UP_ entries, expected >= 100"


# ---------------------------------------------------------------------------
# Category: Cooking/food products
# User confirmed: harvestable plant icons correct
# ---------------------------------------------------------------------------

class TestIconMapFoodProducts:
    """Cooking/food items have correct DDS paths."""

    def test_food_blob(self, icon_map):
        _assert_in_map(icon_map, "FOOD_V_BLOB", "TEXTURES/UI/FRONTEND/ICONS/COOKINGPRODUCTS/PRODUCT.REFINED.HONEY.DDS")

    def test_food_gek(self, icon_map):
        _assert_in_map(icon_map, "FOOD_V_GEK", "TEXTURES/UI/FRONTEND/ICONS/COOKINGPRODUCTS/PRODUCT.MILK.DDS")

    def test_food_coverage(self, icon_map):
        """Food items (FOOD_) should have good coverage."""
        food_count = sum(1 for k in icon_map if k.startswith("FOOD_"))
        assert food_count >= 100, f"Only {food_count} FOOD_ entries, expected >= 100"


# ---------------------------------------------------------------------------
# Category: Fish items
# In icon_map but user reports no icons on Windows — extraction OK, resolution issue
# ---------------------------------------------------------------------------

class TestIconMapFish:
    """Fish items have correct DDS paths in icon_map."""

    def test_fishcore(self, icon_map):
        _assert_in_map(icon_map, "FISHCORE", "TEXTURES/UI/FRONTEND/ICONS/U4PRODUCTS/PRODUCT.FISHCORE.DDS")

    def test_fishbait_1(self, icon_map):
        _assert_in_map(icon_map, "FISHBAIT_1", "TEXTURES/UI/FRONTEND/ICONS/PRODUCTS/PRODUCT.FISHBAIT.1.DDS")

    def test_fish_coverage(self, icon_map):
        """All FISH items should be in icon_map."""
        fish_count = sum(1 for k in icon_map if "FISH" in k and not k.startswith("^"))
        assert fish_count >= 20, f"Only {fish_count} fish entries, expected >= 20"


# ---------------------------------------------------------------------------
# Category: Expedition rewards
# In icon_map but user reports no icons on Windows — extraction OK, resolution issue
# ---------------------------------------------------------------------------

class TestIconMapExpeditionRewards:
    """Expedition reward items have correct DDS paths in icon_map."""

    def test_expd_backpack(self, icon_map):
        _assert_in_map(icon_map, "EXPD_BACKPACK01", "TEXTURES/UI/FRONTEND/ICONS/SPECIALSHOP/SPECIAL.EXPEDITION.BACKPACK01.DDS")

    def test_expd_ship(self, icon_map):
        _assert_in_map(icon_map, "EXPD_SHIP01", "TEXTURES/UI/FRONTEND/ICONS/SPECIALSHOP/SPECIAL.EXPEDITION.SHIP01.DDS")

    def test_expd_coverage(self, icon_map):
        """All EXPD_ items should be in icon_map."""
        expd_count = sum(1 for k in icon_map if k.startswith("EXPD_"))
        assert expd_count >= 150, f"Only {expd_count} EXPD_ entries, expected >= 150"


# ---------------------------------------------------------------------------
# KNOWN GAPS: Items NOT in icon_map (documented for Phase 2 fixes)
# ---------------------------------------------------------------------------

class TestIconMapKnownGaps:
    """Document items known to be missing from icon_map.

    These tests verify the gaps EXIST (are not accidentally fixed).
    When a gap is fixed in Phase 2, the corresponding test should be
    updated to assert the new mapping.
    """

    def test_proc_items_not_in_map(self, icon_map):
        """PROC_* procedural items are NOT in icon_map (known gap)."""
        proc_ids = [
            "PROC_BIO", "PROC_FOSS", "PROC_PLNT", "PROC_FARM",
            "PROC_SEA", "PROC_FEAR", "PROC_SALV", "PROC_BONE",
        ]
        for pid in proc_ids:
            assert pid not in icon_map, f"{pid} unexpectedly in icon_map"
            assert "^" + pid not in icon_map, f"^{pid} unexpectedly in icon_map"
